name: reportes_unimayor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  dart_jsonwebtoken: 3.2.0
  flutter_riverpod: 2.6.1
  go_router: 16.1.0
  google_fonts: 6.2.1
  riverpod_annotation: 2.6.1
  firebase_core: ^3.15.1
  firebase_auth: 5.7.0
  firebase_messaging: 15.2.9
  flutter_local_notifications: 19.3.0
  mobile_scanner: 7.0.1
  flutter_secure_storage: 9.2.4
  record: 6.0.0
  just_audio: 0.10.4
  path_provider: 2.1.5
  path: 1.9.1
  flutter_dotenv: 5.2.1
  google_sign_in: 6.1.1
  url_launcher: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  riverpod_generator: 2.6.5
  build_runner: 2.5.4
  custom_lint: 0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
